export const ErrorCodes = {
  // Authentication & Authorization
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',

  // Validation
  VAL_INVALID_INPUT: 'VAL_INVALID_INPUT',
  VAL_MISSING_FIELD: 'VAL_MISSING_FIELD',
  VAL_INVALID_FORMAT: 'VAL_INVALID_FORMAT',
  VAL_INVALID_ID: 'VAL_INVALID_ID',
  VAL_DUPLICATE_FIELD: 'VAL_DUPLICATE_FIELD',
  VAL_PASSWORD_TOO_WEAK: 'VAL_PASSWORD_TOO_WEAK',

  // Resource
  RES_NOT_FOUND: 'RES_NOT_FOUND',
  RES_ALREADY_EXISTS: 'RES_ALREADY_EXISTS',
  RES_CONFLICT: 'RES_CONFLICT',

  // Business Logic
  BUS_RULE_VIOLATION: 'BUS_RULE_VIOLATION',
  BUS_INSUFFICIENT_FUNDS: 'BUS_INSUFFICIENT_FUNDS',
  BUS_INVALID_OPERATION: 'BUS_INVALID_OPERATION',
  BUS_LIMIT_EXCEEDED: 'BUS_LIMIT_EXCEEDED',

  // Payment
  PAY_PAYMENT_FAILED: 'PAY_PAYMENT_FAILED',
  PAY_INVALID_METHOD: 'PAY_INVALID_METHOD',

  // System
  SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
  SYS_DATABASE_ERROR: 'SYS_DATABASE_ERROR',
  SYS_SERVICE_UNAVAILABLE: 'SYS_SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
